In [1]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
training_set, test_set = mnist.load_data()
X_train, y_train = training_set
X_test, y_test = test_set
print(X_train.shape)

(60000, 28, 28)


In [3]:
# Dla obrazow w skali szarosci tensorflow przyjmuje dodatkowy wymiar na końcu - liczba kanałów, w RGB jest to 3, a w skali szarości 1
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

print(X_train.shape)

(60000, 28, 28, 1)


In [ ]:
# Skalowanie pikseli na zakres 0.0 - 1.0, obraz jest w skali szarości, gdzie wartość pikseli jest reprezentowana na ośmiu bitach
X_train = X_train.astype(np.float) / 255.0  
X_test = X_test.astype(np.float) / 255.0

In [4]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [6]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [8]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 3s 5ms/step - loss: 15.4697 - accuracy: 0.7848 - val_loss: 6.0739 - val_accuracy: 0.8717
Epoch 2/30
375/375 [==============================] - 2s 6ms/step - loss: 5.4593 - accuracy: 0.8715 - val_loss: 4.5783 - val_accuracy: 0.8852
Epoch 3/30
375/375 [==============================] - 2s 7ms/step - loss: 4.2866 - accuracy: 0.8809 - val_loss: 3.9953 - val_accuracy: 0.8904
Epoch 4/30
375/375 [==============================] - 2s 5ms/step - loss: 3.7718 - accuracy: 0.8833 - val_loss: 3.5099 - val_accuracy: 0.8978
Epoch 5/30
375/375 [==============================] - 2s 4ms/step - loss: 3.4633 - accuracy: 0.8854 - val_loss: 3.4653 - val_accuracy: 0.8972
Epoch 6/30
375/375 [==============================] - 2s 5ms/step - loss: 3.1164 - accuracy: 0.8884 - val_loss: 2.9478 - val_accuracy: 0.8967
Epoch 7/30
375/375 [==============================] - 2s 4ms/step - loss: 2.9591 - accuracy: 0.8893 - val_loss: 3.0511 - val_accuracy: 0.8910
Epoch

In [9]:
from sklearn.metrics import classification_report, confusion_matrix

y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 2ms/step
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       980
           1       0.92      0.98      0.95      1135
           2       0.84      0.88      0.86      1032
           3       0.96      0.57      0.72      1010
           4       0.96      0.84      0.89       982
           5       0.69      0.90      0.78       892
           6       0.90      0.94      0.92       958
           7       0.84      0.94      0.89      1028
           8       0.86      0.84      0.85       974
           9       0.87      0.87      0.87      1009

    accuracy                           0.87     10000
   macro avg       0.88      0.87      0.87     10000
weighted avg       0.88      0.87      0.87     10000

[[ 943    0    1    1    0   11   13    4    7    0]
 [   0 1108   15    0    0    1    3    2    5    1]
 [   6   27  908    1    8   12   20   27   18    5]
 [   6   19   76  579    3 

## MLP

In [10]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 64)                50240     
                                                                 
 dense_3 (Dense)             (None, 128)               8320      
                                                                 
 dense_4 (Dense)             (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [12]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 5s 7ms/step - loss: 0.7270 - accuracy: 0.7735 - val_loss: 0.4526 - val_accuracy: 0.8636
Epoch 2/30
375/375 [==============================] - 2s 6ms/step - loss: 0.4669 - accuracy: 0.8571 - val_loss: 0.4160 - val_accuracy: 0.8686
Epoch 3/30
375/375 [==============================] - 2s 6ms/step - loss: 0.4154 - accuracy: 0.8710 - val_loss: 0.3760 - val_accuracy: 0.8892
Epoch 4/30
375/375 [==============================] - 4s 10ms/step - loss: 0.3862 - accuracy: 0.8810 - val_loss: 0.3585 - val_accuracy: 0.8907
Epoch 5/30
375/375 [==============================] - 4s 10ms/step - loss: 0.3696 - accuracy: 0.8845 - val_loss: 0.3536 - val_accuracy: 0.8861
Epoch 6/30
375/375 [==============================] - 3s 9ms/step - loss: 0.3598 - accuracy: 0.8884 - val_loss: 0.3448 - val_accuracy: 0.8938
Epoch 7/30
375/375 [==============================] - 3s 7ms/step - loss: 0.3341 - accuracy: 0.8950 - val_loss: 0.3266 - val_accuracy: 0.8992
Epoc

In [13]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 4ms/step
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       980
           1       0.98      0.98      0.98      1135
           2       0.95      0.92      0.93      1032
           3       0.91      0.93      0.92      1010
           4       0.94      0.93      0.93       982
           5       0.89      0.93      0.91       892
           6       0.95      0.95      0.95       958
           7       0.93      0.94      0.94      1028
           8       0.91      0.90      0.90       974
           9       0.91      0.89      0.90      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 957    0    2    1    1    5    7    1    3    3]
 [   0 1113    2    5    1    3    3    2    6    0]
 [   9    5  947   19    6    4   10   11   18    3]
 [   0    1   14  935    1 

## Convolutional Neural Network

In [14]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_3 (Flatten)         (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)             

In [15]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 24s 60ms/step - loss: 1.2451 - accuracy: 0.8357 - val_loss: 0.1017 - val_accuracy: 0.9697
Epoch 2/30
375/375 [==============================] - 23s 62ms/step - loss: 0.1818 - accuracy: 0.9428 - val_loss: 0.0709 - val_accuracy: 0.9789
Epoch 3/30
375/375 [==============================] - 23s 61ms/step - loss: 0.1344 - accuracy: 0.9584 - val_loss: 0.0597 - val_accuracy: 0.9808
Epoch 4/30
375/375 [==============================] - 20s 54ms/step - loss: 0.1128 - accuracy: 0.9651 - val_loss: 0.0534 - val_accuracy: 0.9832
Epoch 5/30
375/375 [==============================] - 20s 55ms/step - loss: 0.0989 - accuracy: 0.9694 - val_loss: 0.0522 - val_accuracy: 0.9840
Epoch 6/30
375/375 [==============================] - 19s 52ms/step - loss: 0.0880 - accuracy: 0.9729 - val_loss: 0.0459 - val_accuracy: 0.9862
Epoch 7/30
375/375 [==============================] - 19s 52ms/step - loss: 0.0796 - accuracy: 0.9754 - val_loss: 0.0408 - val_accuracy:

In [17]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 2s 6ms/step
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.99      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       0.99      0.99      0.99       958
           7       0.98      0.99      0.98      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.98      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 976    0    2    0    0    0    1    1    0    0]
 [   0 1132    2    1    0    0    0    0    0    0]
 [   0    1 1021    1    0    0    3    6    0    0]
 [   0    0    1 1003    0 